"""Refresh the existing database guide's live section using a read-only query."""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from manage_gfs import ROOT, connect

BEGIN_MARKER = "<!-- BEGIN GENERATED LIVE SCHEMA -->"
END_MARKER = "<!-- END GENERATED LIVE SCHEMA -->"


def merge_snapshot(existing, snapshot):
    """Replace only the managed section; never replace human-written guidance."""
    section = BEGIN_MARKER + "\n" + snapshot.rstrip() + "\n" + END_MARKER
    if BEGIN_MARKER not in existing and END_MARKER not in existing:
        return existing.rstrip() + "\n\n" + section + "\n"
    if existing.count(BEGIN_MARKER) != 1 or existing.count(END_MARKER) != 1:
        raise ValueError("Invalid live-schema section markers; guide left unchanged")
    before, remainder = existing.split(BEGIN_MARKER, 1)
    if END_MARKER not in remainder:
        raise ValueError("Live-schema section markers are out of order; guide left unchanged")
    _, after = remainder.split(END_MARKER, 1)
    return before + section + after


def cell(value):
    if isinstance(value, datetime):
        value = value.astimezone(timezone.utc).isoformat()
    return str(value).replace("|", "\\|").replace("\n", " ") if value is not None else ""


def refresh_schema_document(destination=None):
    destination = Path(destination) if destination else ROOT / "DATABASE_AGENT_GUIDE.md"
    # Require the canonical guide to exist rather than silently creating a new document.
    existing = destination.read_text(encoding="utf-8")
    with connect() as connection:
        # All catalog definitions and counts reflect one committed snapshot.
        connection.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY")
        database = connection.execute("SELECT current_database()").fetchone()[0]
        objects = connection.execute("""
            SELECT c.oid, c.relname, c.relkind
            FROM pg_catalog.pg_class AS c
            JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
            ORDER BY c.relname
        """, ("project",)).fetchall()
        lines = [
            "## Live schema snapshot", "",
            f"Live database: `{cell(database)}`. Schema: `project`.", "",
            "Verified at: " + datetime.now(timezone.utc).isoformat(timespec="seconds") + ".", "",
            "Generated by `data_management/model_forecasts/schema_document.py` using",
            "a read-only connection loaded from the repository-root `.env`.",
            "This is the committed live catalog, not a list of proposed migrations.", "",
            "Human definitions, interpretation and safe query patterns are retained",
            "in the preceding sections of this guide.", "",
            "Refresh this section after every database modification, including imports.", "",
            "### Object inventory", "",
            "| Object | Kind |", "| --- | --- |",
        ]
        kinds = {"r": "table", "p": "partitioned table", "v": "view", "m": "materialized view", "f": "foreign table"}
        for _, name, kind in objects:
            lines.append(f"| `project.{cell(name)}` | {kinds[kind]} |")
        lines.extend(["", "### External-model import status", ""])
        names = {name for _, name, _ in objects}
        if "external_model_source" in names:
            sources = connection.execute("""
                SELECT model, count(*), min(run_time_utc), max(run_time_utc)
                FROM project.external_model_source GROUP BY model ORDER BY model
            """).fetchall()
            lines.extend(["| Model | Source subsets | First run (UTC) | Last run (UTC) |", "| --- | ---: | --- | --- |"])
            for model, count, first, last in sources:
                lines.append(f"| {cell(model)} | {count:,} | {cell(first)} | {cell(last)} |")
            if not sources:
                lines.append("| No imported sources | 0 | | |")
        else:
            lines.append("`project.external_model_source` has not been created.")
        if "external_model_temperature" in names:
            count = connection.execute("SELECT count(*) FROM project.external_model_temperature").fetchone()[0]
            lines.extend(["", f"Temperature extract rows: **{count:,}** (actual count at verification time)."])
        lines.extend(["", "### Live object definitions", ""])
        for oid, name, kind in objects:
            columns = connection.execute("""
                SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod),
                       a.attnotnull, pg_catalog.pg_get_expr(d.adbin, d.adrelid),
                       a.attidentity, a.attgenerated
                FROM pg_catalog.pg_attribute AS a
                LEFT JOIN pg_catalog.pg_attrdef AS d
                       ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped
                ORDER BY a.attnum
            """, (oid,)).fetchall()
            lines.extend([f"#### `project.{name}`", "", f"Kind: {kinds[kind]}.", "",
                          "| Column | PostgreSQL type | Nullable | Default / generation |",
                          "| --- | --- | --- | --- |"])
            for column, data_type, not_null, default, identity, generated in columns:
                expression = default or ""
                if identity:
                    expression = "identity " + ("ALWAYS" if identity == "a" else "BY DEFAULT")
                elif generated:
                    expression = "generated: " + expression
                lines.append(f"| `{cell(column)}` | `{cell(data_type)}` | {'No' if not_null else 'Yes'} | {cell(expression)} |")
            if kind in ("v", "m"):
                definition = connection.execute("SELECT pg_catalog.pg_get_viewdef(%s, true)", (oid,)).fetchone()[0]
                lines.extend(["", "View definition:", "", "```sql", definition, "```"])
                lines.extend(["", "View nullability is catalog metadata, not proof that joined values are non-null."])
            constraints = connection.execute("""
                SELECT conname, pg_catalog.pg_get_constraintdef(oid, true)
                FROM pg_catalog.pg_constraint WHERE conrelid = %s ORDER BY conname
            """, (oid,)).fetchall()
            if constraints:
                lines.extend(["", "Constraints (including foreign-key join contracts):", ""])
                lines.extend(f"- `{cell(label)}`: `{cell(definition)}`" for label, definition in constraints)
            indexes = connection.execute("""
                SELECT pg_catalog.pg_get_indexdef(indexrelid)
                FROM pg_catalog.pg_index WHERE indrelid = %s ORDER BY indexrelid
            """, (oid,)).fetchall()
            if indexes:
                lines.extend(["", "Indexes:", "", "```sql"])
                lines.extend(definition + ";" for (definition,) in indexes)
                lines.append("```")
            lines.append("")
    # This is a derived documentation artifact, not a database operation.
    # Re-read before writing to preserve any human edits made during the query.
    existing = destination.read_text(encoding="utf-8")
    destination.write_text(merge_snapshot(existing, "\n".join(lines)), encoding="utf-8")
    return destination


if __name__ == "__main__":
    try:
        print("Updated: " + str(refresh_schema_document()))
    except Exception:
        print("Schema documentation refresh failed. Check DB access and output-file permissions; no database writes were performed.", file=sys.stderr)
        sys.exit(1)
